server:
  port: 8686

app:
  vue: http://localhost:8787
  
jwt:
  # secret 生产环境请自行生成 UUID
  secret: "50da066e-6080-40f5-a173-86bd27d4f674"
  # token 过期时间（毫秒）默认 30min
  duration: 1800000

mybatis-flex:
  datasource:
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/beidou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
  global-config:
    print-banner: false

# swagger路径：http://localhost:8686/swagger-ui/index.html
springdoc:
  # 生产环境需要关闭这2个参数
  api-docs:
    # 是否开启OpenApi，如果为false，则SwaggerUI也会被禁用
    enabled: true
  swagger-ui:
    # 是否开启SwaggerUI，依赖OpenApi的开启
    enabled: true

spring:
  flyway:
    # 禁用版本验证
    validate-on-migrate: false
  servlet:
    # 默认文件大小就是这里设置的，按需修改
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

gms:
  service:
    # zh-CN en-US
    language: zh-CN
    rate-limit:
      # 是否开启限流
      enabled: false
      # 每ip多少时间内最大请求数
      limit: 10
      # 每ip最大请求数多少时间重置，单位ms
      duration: 1000
      # 是否自动封禁
      auto-ban: false
    # 公网ip
    wan-host: 127.0.0.1
    # 局域网ip
    lan-host: 127.0.0.1
    # 本地ip
    localhost: 127.0.0.1
    # 客户端登录端口
    login-port: 8484
